### ISSUE TITLE
missing file based on yr dockerfile

### ISSUE THREAD

**Issue by elRadix** [JorinL/presence#1]
/presence/presence_main.sh - its looking for this script

can you pls share how you run you docker?

```
version: "2"
services:
  presence:
    container_name: presence
    image: myimage/presence:latest
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Brussels
    volumes:
      - /opt/docker/presence/config:/presence
    restart: always
```
